falcosecurity/rules

build/registry/tag.go
build/registry/tag_test.go

This adds, e.g. the tag `0` when we push something like `0.1`, also ensures that pre releases are also pushed, even if not latest.

fix(ci): also push major floating tag and pre release

---

build/registry/requirements.go

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
Use the `engine_version` instead of `required_engine_version` as a key when setting the engine version requirement in the config layer of the OCI artifacts.

fix(registry/config): set correct key for engine version in config layer

---

RELEASE.md

Signed-off-by: Jason Dellaluce <jasondellaluce@gmail.com>
Providing correct guidelines for releasing and versioning rulesets is crucial for ensuring that Falco behaves correctly, specially considering the degree of automation that falcoctl will introduce.

docs(RELEASE.md): add initial release guidelines

---

build/registry/go.mod
build/registry/go.sum

This should be a no-op, since no relevant changes have been introduced in falcoctl that can have effect to the CI.
However, this PR can help to double-check if our expectation is correct. It will also make the version we use here close the the upcoming falcoctl release (that should happens in a few days).
/cc @LucaGuerra 
/cc @jasondellaluce 
cc @alacuku

build(build/registry): bump falcoctl

---

rules/falco_rules.yaml

/kind cleanup
/area rules
- update k8s registry domain
part of https://github.com/kubernetes/k8s.io/issues/4780
/assign @leogr 
Not sure if we will need to keep both for while. will wait for some feedback
Fixes #

update k8s registry domain

---

rules/falco_rules.yaml

/kind cleanup
/area rules
This sets three rules as disabled by default, each for a different reason:
- `Contact EC2 Instance Metadata Service From Container`: without custom overrides, the rule contains the unrolled condition `container and not container`, which means that the rule never triggers at default and just wastes evaluation time.
- `Outbound Connection to C2 Servers`: without custom overrides, the condition will require one of `fd.sip` and `fd.sip.name` to be contained in empty lists, which is impossible, meaning that the rule never triggers at default and just wastes evaluation time.
- `Java Process Class File Download`: This matches the `recvfrom` …

update(falco_rules): disable three rules by default

---

rules/falco_rules.yaml

The process is called by systemd regularly and write to /var/lib/rpm/rpmdb.sqlite-shm.  This will quiet down the event log on RHEL 9 and possibly other RHEL versions.
/kind bug
/area rules
Signed-off-by: Petter Reinholdtsen <pere@hungry.com>

Added dnf-automatic to list of rpm_binaries

---

rules/falco_rules.yaml

Signed-off-by: Thomas Labarussias <issif+github@gadz.org>
/kind bug
> /kind design
/area rules
> /area build
The `falco_rules.yaml` contained 2 lists for `docker_binaries`, without an append, the first was totally override. I merged them into a single one.
Fixes #

merge the two docker_binaries into a single one, the first was overrided

---

rules/falco_rules.yaml

> /kind bug
> /kind design
/area rules
> /area build
Fixes #
**Special notes for your reviewer**: the rule `Outbound or Inbound Traffic not to Authorized Server Process and Port` depends `authorized_server_binary` list, which is missing so I add it.

fix(rules): add authorized_server_binary list

---

rules/falco_rules.yaml

> /kind bug
> /kind design
/kind feature
/area rules
> /area build
add new `umount` macro
Fixes #

new(rules): add umount macro

---

rules/falco_rules.yaml

Signed-off-by: <darryk10>stefano.chierici@sysdig.com
> /kind bug
> /kind design
/area rules
> /area build
This PR adds the binary `netcat` into the macro `network_tool_binaries` to add detection for this case.
Fixes #

Macro(network_tool_binaries) Added netcat binary

---

rules/falco_rules.yaml

Thanks to @edirgarcia for the idea : D
/kind feature
The list of package managers does not include Conda, a common manager for Python packages and lower-level depenencies.
/area rules
Without this change, some package manager use cases may be missed,
No issue included at the moment

Adding conda as a package manager for Python that could be used

---

rules/falco_rules.yaml

> /kind bug
> /kind design
/kind feature
/area rules
> /area build
Adding rules for running Falco on Azure Kubernetes Services (AKS) with less false positives.
Fixes #
I hope this is fine and I did not miss any rules for contributing.

Adding AKS rules

---

build/registry/index.go
build/registry/testdata/registry.yaml

/kind bug
> /kind design
> /area rules
/area registry
> /area build
The artifact name is added to the list of keywords when generating the `index.yaml` file. It could happen that the list of keywords is in ` registry.yaml` already contains the artifact name. This fix checks if the artifact name is contained in the keywords, if not adds it
Fixes #

 fix(registry/index): do not add artifact name to keywords if already present

---

rules/falco_rules.yaml

> /area rules
Private key candidates will be searched by attacker are insufficient. At least, Ubuntu 22.04 may create the following key by default.
- `id_ed25519`
- `id_ecdsa`

Rule: Search Private Keys or Passwords / Add private key candidates

---

rules/falco_rules.yaml

**Description**
Add mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi to the known_aks_mount_in_privileged_containers macro to suppress unnecessary alerts when using azurefile mounts.  Also added additional parentheses to clarify expected behavior of and/or conditions.
Fixes https://github.com/falcosecurity/rules/issues/69
/kind feature
/area rules

Support azurefile-csi as known_aks_mount_in_privileged_containers

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
As a first step tag all rules that are disabled by default w/ `maturity_sandbox` level as part of phase 1 of implementing the rules maturity framework 
https://github.com/falcosecurity/rules/blob/main/proposals/20230605-rules-adoption-management-maturity-framework.md. Subsequently re-audit these rules and consider elevating some to `maturity_incubating` while providing compelling reasons and explanations. …

cleanup(rules): initially tag all rules disabled by default w/ maturity_sandbox level

---

.github/workflows/release.yaml

/kind feature
/area registry
/area build
This PR introduces the signature of the rules' OCI artifact, usign [cosign](https://github.com/sigstore/cosign).
Fixes #65 
This is part of the work for securing the Falco supply chain. In detail of signatures of Falco OCI artifacts, you can read [here](https://github.com/falcosecurity/falcoctl/issues/174#issuecomment-1499338972).

Introduce OCI artifacts signatures

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Second round of initially tagging rules w/ maturity_stable.
* enhanced desc
* more complete output fields
* cleanup of tags if applicable
* add new maturity_stable tag
@LucaGuerra @loresuso @jasondellaluce
Fixes #

cleanup(rules): initial tagging of stable rules round2

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Third round of initially tagging rules w/ maturity_stable.
* enhanced desc
* more complete output fields
* cleanup of tags if applicable
* add new maturity_stable tag
@LucaGuerra @loresuso @jasondellaluce
Fixes #

cleanup(rules): initial tagging of stable rules round3

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Initially tag remaining rules either w/ sandbox or incubating maturity. First pass, will be re-balanced and corrected as needed after each rule has been tagged alongside general improvements to rules conditions, descriptions or output fields consistency changes that will follow.
@LucaGuerra I bucketed more rules here as all of the write rules require much more work to lay the foundation to effectively …

cleanup(rules): initial tagging of sandbox or incubating rules round2

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Fourth round of initially tagging rules w/ maturity_stable.
* enhanced desc
* more complete output fields
* cleanup of tags if applicable
* add new maturity_stable tag
@LucaGuerra @loresuso @jasondellaluce
Fixes #

cleanup(rules): initial tagging of stable rules round4

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
All credits to @nigeldouglas-itcarlow ❤️  Amazing job Nigel, truly!
https://falco.org/blog/falco-nist-controls/ …

new(rules): initial tagging of PCI DSS and NIST related rules

---

rules/falco_rules.yaml

https://falco.org/docs/rules/style-guide/
> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
@leogr please review with …

cleanup(rules): adjust output fields wrt new style guide

---

rules/falco_rules.yaml

The fd.types field introduced in libs 0.12.0 allows us to improve the reverse shell rule so it fires only once all three of stdout/stderr/stdin are redirected.
> /kind bug
> /kind design
/area rules
> /area build
> /area …

update(rules): comment how to reduce reverse shell detection noise

---

build/registry/cmd.go
build/registry/oci.go

/kind feature
/area registry
/area build
This PR introduces the return of the built OCI artifact's digest.
The digest can later be used to securely reference it. 
Fixes #63 
This is part of the work for securing the Falco supply chain. In detail of signatures of Falco OCI artifacts, you can read [here](https://github.com/falcosecurity/falcoctl/issues/174#issuecomment-1499338972).
Moreover, this is a very simple implementation. A stage of improvements is open for later.

feat(build/registry): return built oci artifact digest

---

.github/scripts/rules_overview_generator.py
.github/workflows/pages.yaml

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Refactor overview generator in anticipation of splitting rules across multiple files.
**Which issue(s) this PR …

cleanup(ci): update overview generator for multiple rules files in rules dir

---

.github/workflows/rules.yaml

/kind bug
> /kind design
/kind failing-test
> /area rules
> /area build
Try to fix this failing test
https://github.com/falcosecurity/rules/actions/runs/6089979444/job/16573436040 …

fix(.github): do not fail when no PR info found

---

rules/falco-incubating_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
During the latest audit I noticed a major coverage gap in the upstream rules wrt SSH connections. This rule adds yet …

new(rules): add "Disallowed SSH Connection Non Standard Port" rule

---

rules/falco-sandbox_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
See rules `desc`.
@Andreagit97 @darryk10 @loresuso thanks!
Fixes #
**Special notes …

new(rules): BPF Program Not Profiled

---

build/registry/tag.go
build/registry/tag_test.go

/kind bug
/area build
If rules marked as 1.0.0, 1.0.1 and 2.0.0-rc1 are present, when 1.0.2 is released it should still be latest because 2.0.0 is not out yet. Fix the build process to consider this case (note the attached test)
Fixes #

fix(build): update latest even if higher prereleases are present

---

rules/falco-sandbox_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
See rules `desc` and https://github.com/falcosecurity/rules/issues/138.
@darryk10  …

new(rules): Decoding Payload in Container

---

rules/falco-incubating_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
Many of the existing rules focus on sensitive files in the traditional Linux sense, which might not align well with …

new(rules): Exfiltrating Artifacts via Kubernetes Control Plane

---

rules/falco-incubating_rules.yaml

> /kind bug
> /kind design
/kind feature
/area rules
> /area build
This PR takes advantage of a new incoming Falco feature for detecting fileless execution via `memfd_create`. This is a very well known defense evasion technique that threat actors might use to execute malware on victim machines. It has been used in the past, but also pretty recently as reported by these two articles:
- https://cybersecurity.att.com/blogs/labs-research/malware-using-new-ezuri-memory-loader
- …

new(rules): add rule for detecting fileless execution via memfd_create

---

rules/falco-incubating_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
See `desc` and also part of modernizing Falco rules https://github.com/falcosecurity/rules/issues/138.
CC @darryk10 …

new(rules): Change namespace privileges via unshare

---

rules/falco-sandbox_rules.yaml

/kind cleanup
/area rules
As per this discussion: https://github.com/falcosecurity/rules/pull/145#discussion_r1315544548 we can fix the rule name! cc @leogr @incertum 
Fixes #

update(rules/sandbox): fix misleading name

---

rules/falco_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
This PR adds the `containerd_activities` check to the `Clear Log Activities` rule as we have noticed that the rule …

update(rules): add containerd_activities check to Clear Log Activities rule

---

rules/falco-incubating_rules.yaml

/kind feature
/area rules
Fixes #
Initial detection of attempts to use CVE-2023-4911
I'm not aware of away to detect GLIBC versions in these rules, so having to rely on this less common environment variable being set

Add detection for attempts to use CVE-2023-4911

---

.github/dependabot.yml
.github/workflows/pages.yaml
.github/workflows/release.yaml

/kind cleanup
/area rules
- Setup dependabot
- bump cosign installer to v3.2.0 and use always use the latest cosign
/assign @leogr @LucaGuerra 
Fixes #

Setup dependabot and bump cosign installer to v3.2.0 and always use the latest cosign

---

rules/falco-deprecated_rules.yaml

/kind cleanup
/area rules
/area maturity-deprecated
This PR adapts the deprecated rule file to use a SemVer-compatible `required_engine_version`. This change would avoid a deprecation warning in Falco 0.37.0 (see https://github.com/falcosecurity/falco/pull/2992)

update(deprecated_rules): use SemVer `required_engine_version`

---

build/registry/cmd.go

/kind feature
> /kind bug
> /kind design
> /area rules
/area build
Hi team, this PR allows to authenticate to the registry during `update-index` if the credentials are set
**Which …

update(build/registry): allow optional auth to update-index cmd

---

rules/falco-sandbox_rules.yaml

/kind bug
/area rules
**What this PR does / why we need it**: 
This PR updates new bpf cmd format based on changes implemented in https://github.com/falcosecurity/libs/pull/1545
**Which issue(s) this PR fixes**: 
Fixes #203 

Update: bpf cmd format

---

rules/falco-sandbox_rules.yaml

On Fedora 39, events like this is logged:
Notice BPF Program  Not Profiled (bpf_cmd=5 evt_type=bpf user=root
user_uid=0 user_loginuid=-1 process=systemd proc_exepath=/usr/lib/systemd/systemd
parent=<NA> command=systemd --switched-root --system --deserialize=36 rhgb terminal=0
exe_flags=<NA> container_id=host container_name=host)
This is just normal systemd behaviour, and not really interesting to log.  The provided patch include systemd in the list of processes allowed to use BPF without any event logged.
/kind bug
/area rules

update(sandbox): Added systemd to list of programs ignored when using BPF.

---

rules/falco-sandbox_rules.yaml

Every time etckeeper update the git history of the content in /etc/, it update files in /etc/.git/.  This trigger a warning from falco about writes in /etc/ for every time the cron job or package update.  This change tell the write_etc_common macro to ignore all writes under /etc/.git/ by a process whos great grandparent is etckeeper.  The parent is 'git' and the grandparent is 50vcs-commit.
/kind bug
/kind design
/kind feature
/area rules
Signed-off-by: Petter Reinholdtsen <pere@hungry.com>
Setting WIP to get feedback on the approach, in case there is a better way to do this.  I want to create a similar pull request for cups and /etc/cups/printers.conf, and want feedback on the best alternative.

rule(write_etc_common): Ignore writes by etckeeper under /etc/.git/

---

rules/falco-incubating_rules.yaml

/kind bug
/area rules
Some of the docs in the wild of how to reproduce XZ vulnerability relies on patching `liblzma` and having the filename with `patch` suffix, for example - `liblzma.so.5.6.1.patch`, thus this Falco rule doesn't pick this up. Changing rule to match `contains` string resolves the issue.
Some examples of who's using `liblzma.so.5.6.1.patch` name:
- https://github.com/amlweems/xzbot/tree/main/assets
- https://github.com/r0binak/xzk8s/blob/main/Dockerfile#L11

fix: change CVE-2024-3094 to match liblzma contain instead of endswith

---

rules/falco-incubating_rules.yaml
rules/falco-sandbox_rules.yaml

…y incubating
> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
cleanup(rules): transition rule `BPF Program Not Profiled` to maturity incubating as it is considered …

cleanup(rules): transition rule `BPF Program Not Profiled` to maturity incubating

---

.github/workflows/rules.yaml

/kind bug
> /kind design
> /area rules
/area build
This PR aims to address the CI problem discovered in [this …

fix(.github/workflow): strict naming convention for changed rules files

---

rules/OWNERS

After more than a year as a reviewer in the falcosecurity/rules repo and more than 3 years as a contributor in the Falco community, I want to propose myself as a rule approver.
> /kind bug
> /kind design
> /area rules
> /area build
> …

vote: Adding @darryk10 to rules approvers

---

rules/falco_rules.yaml

/kind cleanup
/area rules
This PR proposes some cleanups, see the commits descriptions

Some minor fixes

---

rules/falco-incubating_rules.yaml

/kind cleanup
/area rules
It fixes missing % in "Unexpected UDP Traffic" output rule.
None opened.
Fixes #

fix: Missing % in "Unexpected UDP Traffic" output rule

---

rules/falco_rules.yaml

PR to fix some output issues within the ruleset
> /kind bug
> /kind design
/area rules
> /area build
Fixes #
**Special notes for your …

fix: fixed output issues within the ruleset

---

rules/falco-incubating_rules.yaml

PR to fix some output issues within the incubating ruleset
> /kind bug
> /kind design
/area rules
> /area build
Fixes #
**Special …

fix: fixed output issues within the incubating ruleset

---

rules/falco-sandbox_rules.yaml

> /kind bug
> /kind design
> /area rules
> /area build
Fixes #

fix: fixed output issues within the sandbox ruleset

---

.github/workflows/.yamllint
.github/workflows/yaml-lint.yaml

> /kind bug
> /kind design
/kind failing-test
/area rules
> /area build
This changes line-length limit to 130
Fixes #
**Special notes for your …

changing line length limit to <130

---

rules/falco-incubating_rules.yaml

/kind bug
/area rules
In https://github.com/falcosecurity/rules/pull/208 we changed the type of the `cmd` argument to a flag type because of changes in https://github.com/falcosecurity/libs/pull/1545 , however the libs PR was only modifying the exit event, while this rule refers to the enter event which is still an INT64, thus we still need to use the …

fix(incubating_rules): revert #508

---

rules/falco_rules.yaml

/kind bug
> /kind design
/area rules
> /area build
This PR is to extend the `known_memfd_execution_binaries` with runc since in 1.1.15 of runc, it introduced a …

rules: add runc to known_memfd_execution_binaries

---

.github/workflows/rules.yaml
build/checker/cmd/common.go

/kind bug
/area build
The CI is failing because it's looking for `falcosecurity/falco-no-driver:0.40.0` which [does not exist](https://github.com/falcosecurity/falco/pull/3273). Switch to `falcosecurity/falco`.
Fixes #

fix(ci): use falcosecurity/falco instead of falcosecurity/falco-no-driver

---

rules/falco_rules.yaml

/kind feature
/area rules
K3s is a stripped down version of Kubernetes that bundles dependencies within it, including containerd. It puts containerd files (sockets, tmpmounts, snapshotter overlayfs, etc.) in namespaced, non-standard locations in an attempt to not interfere with a system-wide containerd installation. As a result, the "Clear Log Activities" rule triggers warnings for the bundled containerd. Fix that by including K3s' non-standard paths in the containerd_activities macro.

rules: add support for k3s to containerd_activities macro

---

rules/falco-incubating_rules.yaml
rules/falco_rules.yaml

/kind bug
/area rules
This fixes detection of "Terminal shell in container" for podman running with crun.
Fixes #

fix(rules): add `conmon` to `container_entrypoint` macro.

---

rules/falco_rules.yaml

/kind bug
> /kind design
/area rules
> /area build
OpenSSH version 9.8 ([release notes](https://www.openssh.com/txt/release-9.8)) split the `sshd` binary into `sshd` …

Allow new sshd-session binary to read sensitive files
