falcosecurity/rules

registry.yaml

Use `falco-rules` and `application-rules` names.

update(registry): update rules package names

---

registry.yaml

update(registry): trigger index update

---

registry.yaml

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>

chore(registry.yaml): testing the CI

---

registry.yaml

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>

chore(registry.yaml): testing CI

---

rules/falco_rules.yaml
rules_inventory/rules_overview.md
rules_inventory/scripts/rules_overview_generator.py

Minor updates as we are transitioning repos. Interim manual update of overview markdown doc.
```release-note
cleanup(rules): add missing tags
```

cleanup(rules, rules_inventory): update rules inventory

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Signed-off-by: Roberto Scolaro [roberto.scolaro21@gmail.com](roberto.scolaro21@gmail.com)
Adding basic documentation to the repository.
Fixes #3 

docs: basic documentation

---

README.md

Signed-off-by: Roberto Scolaro <roberto.scolaro21@gmail.com>
> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
I think that now this repo is official and can be used! 😄 
Fixes #

fix(README.md): the repo is now official

---

build/registry/go.mod
build/registry/go.sum

/kind bug
/area build
This fixes the issue that would push `latest` even if we don't expect it: https://github.com/falcosecurity/falcoctl/pull/230
Fixes #

update(ci): update falcoctl repo to 0.3.0-rc5

---

.github/workflows/release.yaml

> /kind bug
/kind cleanup
> /kind design
> /area rules
/area build
The role ARN is not a secret and does not allow any access by itself. However, adding it here explicitly makes it easier to troubleshoot potential issues.
Fixes #

update(ci): use an explicit role instead of a secret

---

README.md

Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
> /kind design
> /area rules
> /area build
Fixes #

docs(README.md): clarifications and improvements

---

rules/falco_rules.yaml

/kind bug
> /kind design
/area rules
> /area build
This rule was built on top of a bug, see https://github.com/falcosecurity/libs/pull/970
Once that one will be merged and Falco can use it, we should merge this PR as well.
For the same reason, some other rules stopped working, like https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L2950 because the flag was not retrieved as string anymore. This makes me think we need a better CI :) 
**Which …

fix(rules): fix ptrace attach and injection rule

---

rules/falco_rules.yaml

/kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Rule "Linux Kernel Module Injection Detected" is limited in scope.
A major refactor of Falco now exposes each syscall Falco's libs supports (including `init_module`) to the end user :)
Official support starts with Falco 0.35.0.
https://github.com/falcosecurity/falco/issues/2443#issuecomment-1471289452
Fixes #
CC @loresuso @LucaGuerra @jasondellaluce …

cleanup(rules)!: refactor kernel module rule

---

rules/falco_rules.yaml

Signed-off-by: Alessandro Brucato [alessandro.brucato@sysdig.com](mailto:alessandro.brucato@sysdig.com)
> /kind bug
> /kind design
/kind rule-create
/area rules
> /area build
The ptrace system call is used by debuggers, such as GDB, to examine a target process. Malicious programs will often try to prevent this by using the ptrace system call first, preventing other programs from using it on them. This rule detects that behavior. Legitimate processes may also do this …

Rule: PTRACE anti-debug attempt

---

.github/workflows/create-comment.yaml

fix(ci): solve issues with create-comment

---

.github/workflows/create-comment.yaml

fix(ci): fix http request body in create-comment 

---

RELEASE.md

docs(RELEASE.md): update versioning guidelines for patch releases

---

.github/compare-rule-files.sh

fix(ci): publish a version check comment event with no changes

---

.github/compare-rule-files.sh
rules/falco_rules.yaml

This syncs the `release/falco-rules-1.0.x` release branch with the following PRs already merged in mainline, with the purpose of tagging a version 1.0.1 of the falco rules:
- https://github.com/falcosecurity/rules/pull/79
- https://github.com/falcosecurity/rules/pull/83

update: sync for falco rules v1.0.1

---

.github/compare-rule-files.sh
.github/workflows/rules.yaml
build/checker/cmd/compare.go
build/checker/cmd/validate.go
rules/falco_rules.yaml

/kind feature
/area build
This PR improves the CI tooling responsible of rules validation and version suggestions, also supporting loading plugin rulesets. This will be used in falcosecurity/plugins for implementing CI checks similar to the ones of this repo.

update(ci): support validating and comparing plugin rules

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Related to Phase 2 of rules maturity framework implementation.
"Re-audit the first round of rules tagged with maturity_sandbox and consider transitioning some to maturity_incubating, with a maximum of 5 rules per PR to enable focused discussions."
@jasondellaluce and @LucaGuerra you will see my suggestion in the yaml changes. Re-audited each rule and at the moment I would only recommend to elevate those 3 rules. …

cleanup(rules): initial transitions of some sandbox rules to incubating

---

.github/workflows/rules.yaml

/kind bug
/area build
Same as https://github.com/falcosecurity/plugins/pull/315.

fix(ci): solve issues with docker

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Initially tag remaining rules either w/ sandbox or incubating maturity. First pass, will be re-balanced and corrected as needed after each rule has been tagged alongside general improvements to rules conditions, descriptions or output fields consistency changes that will follow.
@LucaGuerra 
Fixes #

cleanup(rules): initial tagging of sandbox or incubating rules round3

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Initially tag remaining rules either w/ sandbox or incubating maturity. First pass, will be re-balanced and corrected as needed after each rule has been tagged alongside general improvements to rules conditions, descriptions or output fields consistency changes that will follow.
@LucaGuerra 
Fixes #

cleanup(rules): initial tagging of sandbox or incubating rules round4

---

.github/workflows/pages.yaml

fix(ci): fixed pages generation.

---

.github/workflows/pages.yaml
mkdocs.yml

fix(ci): properly name overview as index.md, as required by mkdocs.

---

.github/PULL_REQUEST_TEMPLATE.md

> /kind bug
> /kind design
> /area rules
> /area build
See https://github.com/falcosecurity/falco-website/issues/1009
Fixes #

docs(.github): update PR template according to the new contrib guide

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Initially tag remaining rules either w/ sandbox or incubating maturity. Final initial pass, will be re-balanced and corrected as needed after each rule has been tagged alongside general improvements to rules conditions, descriptions or output fields consistency changes that will follow.
@LucaGuerra 
@leogr after this one we will conform to the new guidelines when changing tags! …

cleanup(rules): initial tagging of sandbox or incubating rules round5

---

.github/scripts/rules_overview_generator.py

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Adjust overview generator markdown @FedeDP 
Fixes #
**Special notes for your …

cleanup(ci): adjust overview generator markdown

---

rules/falco_rules.yaml

/kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Fix some syntax issues: Ensure that currently disabled rules would always be able to evaluate to something true …

fix(rules): fix some syntax issues and some mitre assignments

---

.github/workflows/pages.yaml
requirements.txt

/kind cleanup
/area build
None
This PR removes the `requirements.txt` file using explicit dependencies in the `deploy-pages` job

cleanup: remove `requirements.txt` file

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Update `container_entrypoint` to reflect changes in behavior based on recent work by @Andreagit97 to improve the …

cleanup(rules): update container_entrypoint (1/n)

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
@darryk10 adjusting priority for "Run shell untrusted". In addition, will propose an update to the …

cleanup(rules): adjust priority for Run shell untrusted

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Update container_entrypoint because of new process tree logic to account for new fall backs for cri-o runtime. …

cleanup(rules): update container_entrypoint (2/n)

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Proposing to re-balance the following rules and assign maturity_incubating.
```
Execution from /dev/shm 
```
-> …

cleanup(rules): re-balance rules, bump several rules to maturity_incubating

---

.github/scripts/rules_overview_generator.py
CONTRIBUTING.md

> /kind bug
> /kind design
> /area rules
> /area build
Refine rules maturity framework, see https://github.com/falcosecurity/rules/issues/126#issuecomment-1696025071. …

docs(CONTRIBUTING): refine rules maturity framework

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Improve `desc` according to the new Style Guide. Prioritized stable and incubating rules (including the ones that are …

cleanup(rules): improve `desc` (1/n)

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Continue enhancing the `desc` of the rules, continuation of https://github.com/falcosecurity/rules/pull/141
**Which …

cleanup(rules): assign `maturity_deprecated` to some rules + improve desc (2/n)

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Lint macro style and ensure consistency (plus all macros are now more future proof).
@darryk10 
**Which issue(s) …

cleanup(rules): lint macro style and ensure consistency

---

rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Re-balance some rules, see https://github.com/falcosecurity/rules/issues/126
```
Execution from /dev/shm
Find AWS …
```

cleanup(rules): re-balance rules and assign maturity_stable to some rules

---

.github/workflows/release.yaml
build/registry/cmd.go
build/registry/go.sum

/kind bug
/area build
Upon release ensure that we're signing the artifact that we're releasing. To do this, the build tool will output the full name that can be used directly by the next step. In addition, make sure cosign has proper permissions by explicitly logging in before running the sign command.
Fixes #

fix(build): sign fully qualified digest upon release

---

rules/falco-incubating_rules.yaml
rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Graduating rule "Disallowed SSH Connection Non Standard Port" according to our assessment here …

cleanup(rules): graduate 'Disallowed SSH Connection Non Standard Port' to maturity_stable

---

rules/falco-sandbox_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
This is another basic auditing rule that can serve as valuable example for adopters, see …

new(rules): Basic Interactive Reconnaissance

---

.github/scripts/rules_overview_generator.py

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
Try fixing some formatting to accomplish a more uniformly formatted overview document.
@FedeDP 
**Which issue(s) …

fix(ci): formatting rules overview doc

---

rules/falco-incubating_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Format unshare rule desc.
Fixes #

cleanup(rules): format unshare rule desc

---

rules/falco-incubating_rules.yaml
rules/falco_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
As per PR title, add fileless execution rule to stable state.
Fixes #
**Special …

update(rules): graduate fileless execution rule

---

rules/falco-sandbox_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Complete the cleanup for rule "Kubernetes Client Tool Launched in Container" @LucaGuerra, ty! 
**Which issue(s) …

fix(rules/sandbox): update rule desc of "Kubernetes Client Tool Launched in Container"

---

registry.yaml

/kind cleanup
/area registry
This will have the net effect of:
1. adding the incubating and sandbox rules to the index
2. adding signature information to the index
Fixes #

update(registry): add signature information for sandbox, incubating and stable rules

---

registry.yaml

/kind bug
/area registry
You can probably feel me facepalming very hard from this.
Fixes #

fix(registry): correct repository name in the signature info

---

README.md

> /kind bug
> /kind design
> /area rules
> /area build
I believe it would be beneficial to users to understand how to enable all the rules present in this repository. …

update(readme): add example helm command line

---

rules/falco-incubating_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
Adding ssh keys to authorized_keys file is a common persistence/escalation technique, as reported …

new(rules): add modification to authorized keys rule

---

archive/application_rules.yaml
build/checker/cmd/common.go
build/checker/cmd/common_test.go
build/checker/cmd/compare.go
build/checker/cmd/compare_test.go
build/checker/cmd/root.go
build/checker/cmd/validate.go
build/checker/main.go
build/registry/cmd.go
build/registry/config_layer.go
build/registry/index.go
build/registry/index_test.go
build/registry/oci.go
build/registry/registry.go
build/registry/requirements.go
build/registry/s3.go
build/registry/tag.go
build/registry/tag_test.go
build/registry/targz.go
registry.yaml
rules/falco-deprecated_rules.yaml
rules/falco-incubating_rules.yaml
rules/falco-sandbox_rules.yaml
rules/falco_rules.yaml

/kind cleanup
/area rules
/area registry
/area build
See https://github.com/falcosecurity/evolution/issues/318
Fixes #

docs: spdx id

---

.github/workflows/pages.yaml

/kind bug
Fixes CI failing with:
> mkdir: cannot create directory ‘docs/’: File exists
Fixes #

fix(ci): fixed pages CI.

---

rules/falco-incubating_rules.yaml
rules/falco-sandbox_rules.yaml
rules/falco_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Fixes #
cc @cpanato @LucaGuerra

update(rules): cleanup k8s.gcr.io

---

.github/workflows/yaml-lint.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
It checks for syntax in falco rules by use of YAML-Lint 
Fixes #144 
**Special …

chore(ci): adding YAML-Lint for falco rules 

---

rules/falco-sandbox_rules.yaml

> /kind bug
/kind cleanup
> /kind design
/area rules
> /area build
Fixes https://github.com/falcosecurity/rules/issues/199
Fixes #
**Special notes …

cleanup(rules-sandbox): remove old ref to k8s.gcr.io

---

rules/falco_rules.yaml

/kind feature
> /kind bug
> /kind design
/area rules
> /area build
This adds a generic macro to the rule to match the pattern in other rules that have a macro included.
**Which …

update: add macro known_drop_and_execute_activities

---

rules/OWNERS

> /kind bug
> /kind design
/area rules
> /area build
Hello everyone, 
I would like to propose myself as a Falco Rules maintainer. I've been involved in the project …

vote: update(OWNERS): add loresuso to approvers

---

.github/scripts/requirements.txt

> /kind bug
/kind cleanup
> /kind design
> /area rules
> /area build
chore: upgrade py deps for rules_overview_generator
CI is currently failing. This fixes the CI.
**Which issue(s) …

chore: upgrade py deps for rules_overview_generator

---

rules/falco-sandbox_rules.yaml

/bug
> /kind design
/area rules
> /area build
Fixes #

fix: fix typo safe_etc_dirs

---

rules/falco-deprecated_rules.yaml
rules/falco-incubating_rules.yaml
rules/falco-sandbox_rules.yaml
rules/falco_rules.yaml

/kind cleanup
/area rules
/area maturity-deprecated
Use a pipe instead to divide args from rule title.
Fixes #

cleanup(rules): drop parentheses around args in rule outputs.

---

OWNERS

> /kind bug
> /kind design
> /area rules
> /area build
Hi folks!
Encouraged by @leogr, I would like to propose myself as maintainer of this repo.
**Which issue(s) this …

vote: docs(OWNERS): add `ekoops` as approver
